export enum NotificationCategory {
  COUPON_PURCHASED = 'COUPON_PURCHASED',
  COUPON_REDEEMED = 'COUPON_REDEEMED',
  COUPON_CREATED = 'COUPON_CREATED',
  POINTS_DELIVERED = 'POINTS_DELIVERED',
  COUPON_EXPIRING_SOON = 'COUPON_EXPIRING_SOON'
}
